/**
 * Comments on an expense.
 *
 * THIS IS THE ONLY MODULE ALLOWED TO WRITE `comments`. Native routes, guest
 * routes and the Splitwise importer all come through these functions, for the
 * same reason every expense write goes through src/domain/expenses.ts: the rules
 * that decide who may say something on whose bill are worth having in one place.
 *
 * Two kinds of row, as Splitwise has them:
 *
 *   user    somebody typed it. Deletable by its author, and only by them.
 *   system  generated by an edit, a delete or a restore. Never accepted over
 *           HTTP, never deletable, and written by `recordExpenseEvent` below.
 *
 * System rows exist because the activity feed is the *global* version of those
 * events, and the question people actually ask is local: you open a six-month-old
 * dinner and want to know why it says 8.99. Importing Splitwise's System history
 * and then never writing another one would leave imported expenses looking
 * annotated and new ones silent, so both are written.
 *
 * A comment is NOT part of the expense. It does not touch `expenses.version`
 * (docs/OFFLINE.md), it cannot conflict, and deleting one moves no money.
 */
import { sql, type RawBuilder } from "kysely";
import type { DB } from "../db/index.ts";
import { db, transaction } from "../db/index.ts";
import { formatAmount } from "./money.ts";
import { isUlid, ulid } from "./ulid.ts";
import { serializeMetadata, type EntityMetadata } from "./metadata.ts";

export type CommentKind = "user" | "system";

/**
 * Carries the HTTP status the route should use.
 *
 * The alternative was every handler re-running the visibility query to decide
 * between 404 and 400, which is two chances to disagree with this module about
 * who can see what.
 *
 * Assigned in the constructor body, not as a parameter property:
 * `--experimental-strip-types` rejects those outright.
 */
export class CommentError extends Error {
  readonly status: 400 | 403 | 404;

  constructor(message: string, status: 400 | 403 | 404) {
    super(message);
    this.status = status;
  }
}

/** The longest comment we will store. Long enough for a paragraph, not an essay. */
export const MAX_COMMENT_LENGTH = 5000;

export interface CommentRecord {
  id: string;
  expenseId: string;
  kind: CommentKind;
  content: string;
  createdAt: string;
  author: { id: string; firstName: string; lastName: string | null };
}

// ---------------------------------------------------------------------------
// Reads
// ---------------------------------------------------------------------------

/**
 * Whether someone may read and write this expense's thread.
 *
 * Deliberately the same rule as `GET /api/v1/expenses/:id`: you are on the bill,
 * or you are currently in the group it belongs to. A group member who is not a
 * participant can still comment, which is the "why am I not on this?" case.
 *
 * A deleted expense is invisible, so its thread is too. The rows stay in the
 * table (soft delete, like everything else) so merge and re-import matching
 * still find them.
 */
export async function canSeeExpense(
  database: DB,
  expenseId: string,
  userId: string,
): Promise<boolean> {
  const expense = await database
    .selectFrom("expenses")
    .select(["id", "group_id"])
    .where("id", "=", expenseId)
    .where("deleted_at", "is", null)
    .executeTakeFirst();

  if (!expense) return false;

  const participant = await database
    .selectFrom("expense_users")
    .select("user_id")
    .where("expense_id", "=", expenseId)
    .where("user_id", "=", userId)
    .executeTakeFirst();

  if (participant) return true;
  if (expense.group_id === null) return false;

  const member = await database
    .selectFrom("group_members")
    .select("user_id")
    .where("group_id", "=", expense.group_id)
    .where("user_id", "=", userId)
    .where("left_at", "is", null)
    .executeTakeFirst();

  return member !== undefined;
}

/** The live thread, oldest first: a conversation reads downwards. */
export async function listComments(
  database: DB,
  expenseId: string,
): Promise<CommentRecord[]> {
  const rows = await database
    .selectFrom("comments")
    .innerJoin("users", "users.id", "comments.user_id")
    .select([
      "comments.id",
      "comments.expense_id",
      "comments.kind",
      "comments.content",
      "comments.created_at",
      "users.id as author_id",
      "users.first_name",
      "users.last_name",
    ])
    .where("comments.expense_id", "=", expenseId)
    .where("comments.deleted_at", "is", null)
    .orderBy("comments.created_at")
    .orderBy("comments.id")
    .execute();

  return rows.map((r) => ({
    id: r.id,
    expenseId: r.expense_id,
    kind: r.kind as CommentKind,
    content: r.content,
    createdAt: r.created_at,
    author: { id: r.author_id, firstName: r.first_name, lastName: r.last_name },
  }));
}

/**
 * `(SELECT COUNT(*) ...)` for the comment count on an expense list row.
 *
 * A correlated subquery rather than a LEFT JOIN + GROUP BY: every list endpoint
 * here already selects a flat row set, and grouping would mean re-deriving the
 * shares aggregation too. `table` is an identifier this code controls.
 */
export function commentCountSql(table = "expenses"): RawBuilder<number> {
  const ref = sql.raw(`${table}.id`);
  return sql<number>`(
    SELECT COUNT(*) FROM comments c
    WHERE c.expense_id = ${ref} AND c.deleted_at IS NULL
  )`;
}

// ---------------------------------------------------------------------------
// Writes
// ---------------------------------------------------------------------------

export interface CreateCommentInput {
  /**
   * Client-minted ULID. A retry with the same id returns the existing row
   * rather than a second comment — the offline idempotency story, same as
   * expenses (docs/OFFLINE.md). Absent: the server mints one.
   */
  id?: string;
  expenseId: string;
  userId: string;
  content: string;
  /** HTTP callers may only write 'user'. System rows come from this module. */
  kind?: CommentKind;
  /** Import passes the Splitwise timestamp so it matches the ULID's time. */
  createdAt?: string;
  /** `{ splitwise_id }` on import, so a second run matches instead of doubling. */
  metadata?: EntityMetadata;
  /** Import writes one summary feed entry per run instead. */
  recordActivity?: boolean;
  /**
   * Import sets this false. It is replaying history, not authorising an action:
   * Splitwise lets somebody comment and then leave the group, and dropping that
   * comment would throw away the only edit history we can ever get.
   */
  enforceVisibility?: boolean;
}

export async function createComment(input: CreateCommentInput): Promise<string> {
  if (input.id !== undefined && !isUlid(input.id)) {
    throw new CommentError("Invalid comment id", 400);
  }

  const content = input.content.trim();
  if (content === "") throw new CommentError("A comment needs something in it", 400);
  if (content.length > MAX_COMMENT_LENGTH) {
    throw new CommentError(`A comment cannot be longer than ${MAX_COMMENT_LENGTH} characters`, 400);
  }

  if (input.enforceVisibility !== false) {
    if (!(await canSeeExpense(db, input.expenseId, input.userId))) {
      throw new CommentError("Not found", 404);
    }
  }

  return transaction(async (trx) => {
    // First writer wins, exactly as createExpense does with a client-minted id.
    if (input.id) {
      const existing = await trx
        .selectFrom("comments")
        .select("id")
        .where("id", "=", input.id)
        .executeTakeFirst();
      if (existing) return existing.id;
    }

    const id = input.id ?? ulid();

    await trx
      .insertInto("comments")
      .values({
        id,
        metadata: serializeMetadata(input.metadata ?? {}),
        expense_id: input.expenseId,
        user_id: input.userId,
        kind: input.kind ?? "user",
        content,
        ...(input.createdAt ? { created_at: input.createdAt } : {}),
      })
      .execute();

    if (input.recordActivity !== false && (input.kind ?? "user") === "user") {
      await recordCommentActivity(trx, {
        expenseId: input.expenseId,
        userId: input.userId,
        commentId: id,
        action: "comment.created",
      });
    }

    return id;
  });
}

/**
 * Soft-deletes a user comment.
 *
 * Author-only, and never a system row: a generated sentence describing an edit
 * is part of the bill's history, and letting the person who made the edit erase
 * the note about it would make the history a lie.
 *
 * Deleting twice is not an error, so a retried offline op resolves rather than
 * failing.
 */
export async function deleteComment(commentId: string, deletedBy: string): Promise<void> {
  if (!isUlid(commentId)) throw new CommentError("Invalid comment id", 400);

  await transaction(async (trx) => {
    const comment = await trx
      .selectFrom("comments")
      .select(["id", "expense_id", "user_id", "kind", "deleted_at"])
      .where("id", "=", commentId)
      .executeTakeFirst();

    if (!comment) throw new CommentError("Not found", 404);
    if (comment.deleted_at) return; // already gone; deleting twice is a no-op

    // Checked before authorship so someone who cannot see the expense at all
    // learns nothing about who wrote what on it.
    if (!(await canSeeExpense(trx, comment.expense_id, deletedBy))) {
      throw new CommentError("Not found", 404);
    }
    if (comment.kind !== "user") {
      throw new CommentError("Generated comments cannot be deleted", 403);
    }
    if (comment.user_id !== deletedBy) {
      throw new CommentError("Only whoever wrote a comment can delete it", 403);
    }

    await trx
      .updateTable("comments")
      .set({ deleted_at: sql`datetime('now')` })
      .where("id", "=", commentId)
      .execute();

    await recordCommentActivity(trx, {
      expenseId: comment.expense_id,
      userId: deletedBy,
      commentId,
      action: "comment.deleted",
    });
  });
}

async function recordCommentActivity(
  trx: DB,
  input: { expenseId: string; userId: string; commentId: string; action: string },
): Promise<void> {
  const expense = await trx
    .selectFrom("expenses")
    .select("group_id")
    .where("id", "=", input.expenseId)
    .executeTakeFirst();

  await trx
    .insertInto("activity")
    .values({
      id: ulid(),
      user_id: input.userId,
      group_id: expense?.group_id ?? null,
      expense_id: input.expenseId,
      action: input.action,
      payload: JSON.stringify({ commentId: input.commentId }),
    })
    .execute();
}

// ---------------------------------------------------------------------------
// System comments
// ---------------------------------------------------------------------------

/**
 * An expense as a thread reader needs to see it: display strings, not ids.
 *
 * Resolving category / group / people to names happens in `snapshotExpense`
 * below so the diff itself stays pure and testable. Nothing here is ledger data;
 * it exists only to be turned into an English sentence.
 */
export interface ExpenseSnapshot {
  description: string;
  details: string | null;
  /** Already formatted with the currency: "25.00 USD". */
  amount: string;
  /** Date only. Nobody wants "the date changed" to be about a timezone. */
  date: string;
  category: string | null;
  /** Group name, or null for a one-on-one expense. */
  group: string | null;
  isPayment: boolean;
  /** Display name -> what they owe, formatted. Sorted by name. */
  shares: Array<{ name: string; owed: string }>;
  /** 'monthly' etc, or null. */
  repeat: string | null;
}

function quote(value: string): string {
  const flat = value.replace(/\s+/g, " ").trim();
  return `"${flat.length > 120 ? `${flat.slice(0, 119)}…` : flat}"`;
}

/**
 * The change list for a system comment, or an empty array if nothing changed.
 *
 * Pure, so the wording is testable without a database. Kept boring and stable on
 * purpose: this text is stored forever and shown next to real conversation, and
 * chasing Splitwise's exact English would mean rewriting stored history every
 * time they reword something.
 */
export function describeExpenseChange(
  before: ExpenseSnapshot,
  after: ExpenseSnapshot,
): string[] {
  const lines: string[] = [];

  if (before.amount !== after.amount) {
    lines.push(`Amount: ${before.amount} → ${after.amount}`);
  }
  if (before.description !== after.description) {
    lines.push(`Description: ${quote(before.description)} → ${quote(after.description)}`);
  }
  if (before.date !== after.date) {
    lines.push(`Date: ${before.date} → ${after.date}`);
  }
  if (before.category !== after.category) {
    lines.push(`Category: ${before.category ?? "none"} → ${after.category ?? "none"}`);
  }
  if (before.group !== after.group) {
    lines.push(
      after.group === null
        ? `Moved out of ${before.group} into one-on-one expenses`
        : before.group === null
          ? `Moved into ${after.group}`
          : `Moved from ${before.group} to ${after.group}`,
    );
  }
  if ((before.details ?? "") !== (after.details ?? "")) {
    lines.push(
      after.details === null || after.details === ""
        ? "Notes removed"
        : before.details === null || before.details === ""
          ? `Notes added: ${quote(after.details)}`
          : `Notes: ${quote(before.details)} → ${quote(after.details)}`,
    );
  }
  if (before.repeat !== after.repeat) {
    lines.push(
      after.repeat === null
        ? "No longer repeats"
        : before.repeat === null
          ? `Now repeats ${after.repeat}`
          : `Repeats ${before.repeat} → ${after.repeat}`,
    );
  }

  const wasOwed = new Map(before.shares.map((s) => [s.name, s.owed]));
  const nowOwed = new Map(after.shares.map((s) => [s.name, s.owed]));

  for (const { name, owed } of after.shares) {
    if (!wasOwed.has(name)) {
      lines.push(`Added ${name}, owing ${owed}`);
    } else if (wasOwed.get(name) !== owed) {
      lines.push(`${name}'s share: ${wasOwed.get(name)} → ${owed}`);
    }
  }
  for (const { name } of before.shares) {
    if (!nowOwed.has(name)) lines.push(`Removed ${name}`);
  }

  return lines;
}

/**
 * Reads an expense as an `ExpenseSnapshot`, inside the caller's transaction.
 *
 * Called twice by `updateExpense`: once before the write and once after, so the
 * diff describes what actually landed rather than what was asked for (the split
 * engine may have moved a cent that the request never mentioned).
 */
export async function snapshotExpense(
  trx: DB,
  expenseId: string,
): Promise<ExpenseSnapshot | null> {
  const expense = await trx
    .selectFrom("expenses")
    .leftJoin("categories", "categories.id", "expenses.category_id")
    .leftJoin("groups", "groups.id", "expenses.group_id")
    .select([
      "expenses.description",
      "expenses.details",
      "expenses.cost_minor",
      "expenses.currency_code",
      "expenses.date",
      "expenses.is_payment",
      "expenses.repeat_interval",
      "categories.name as category_name",
      "groups.name as group_name",
    ])
    .where("expenses.id", "=", expenseId)
    .executeTakeFirst();

  if (!expense) return null;

  const decimals = await decimalPlacesFor(trx, expense.currency_code);

  const shares = await trx
    .selectFrom("expense_users")
    .innerJoin("users", "users.id", "expense_users.user_id")
    .select([
      "users.id",
      "users.first_name",
      "users.last_name",
      "expense_users.owed_share_minor",
    ])
    .where("expense_users.expense_id", "=", expenseId)
    .execute();

  return {
    description: expense.description,
    details: expense.details,
    amount: `${formatAmount(expense.cost_minor, decimals)} ${expense.currency_code}`,
    date: expense.date.slice(0, 10),
    category: expense.category_name,
    group: expense.group_name,
    isPayment: expense.is_payment === 1,
    repeat: expense.repeat_interval,
    shares: shares
      .map((s) => ({
        name: [s.first_name, s.last_name].filter(Boolean).join(" "),
        owed: `${formatAmount(s.owed_share_minor, decimals)} ${expense.currency_code}`,
      }))
      .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0)),
  };
}

export type ExpenseEvent =
  | { kind: "updated"; before: ExpenseSnapshot; after: ExpenseSnapshot }
  | { kind: "deleted" }
  | { kind: "restored" };

/**
 * Hangs a system comment on an expense, best-effort.
 *
 * BEST-EFFORT IS THE CONTRACT. The ledger is the invariant; the sentence is
 * not. A failure building or writing the note is swallowed and logged rather
 * than rolling back the expense write it describes — an edit that fails because
 * its own footnote failed would be a far worse bug than a missing footnote.
 *
 * Runs inside the caller's transaction so a note never survives an edit that
 * was itself rolled back.
 */
export async function recordExpenseEvent(
  trx: DB,
  input: { expenseId: string; actorId: string; event: ExpenseEvent },
): Promise<void> {
  try {
    const actor = await trx
      .selectFrom("users")
      .select(["first_name", "last_name"])
      .where("id", "=", input.actorId)
      .executeTakeFirst();

    const who = actor
      ? [actor.first_name, actor.last_name].filter(Boolean).join(" ")
      : "Somebody";

    let content: string;
    if (input.event.kind === "updated") {
      const lines = describeExpenseChange(input.event.before, input.event.after);
      // An edit that changed nothing visible does not deserve a note.
      if (lines.length === 0) return;
      content = `${who} updated this expense:\n${lines.map((l) => `- ${l}`).join("\n")}`;
    } else if (input.event.kind === "deleted") {
      content = `${who} deleted this expense.`;
    } else {
      content = `${who} restored this expense.`;
    }

    await trx
      .insertInto("comments")
      .values({
        id: ulid(),
        expense_id: input.expenseId,
        user_id: input.actorId,
        kind: "system",
        content,
      })
      .execute();
  } catch (err) {
    console.error(
      `Could not record a system comment on expense ${input.expenseId}:`,
      err instanceof Error ? err.message : err,
    );
  }
}

async function decimalPlacesFor(trx: DB, currencyCode: string): Promise<number> {
  const row = await trx
    .selectFrom("currencies")
    .select("decimal_places")
    .where("code", "=", currencyCode)
    .executeTakeFirst();
  // currency_code is a foreign key, so this branch means the currencies table
  // was not seeded; 2 keeps the sentence readable rather than throwing.
  return row?.decimal_places ?? 2;
}
